# Generated by Django 5.0.3 on 2024-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_stationmodel_trainsmodel_reservationmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='reservastion_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='schedule_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='station_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainsmodel',
            name='train_id',
            field=models.TextField(),
        ),
    ]
