# Generated by Django 4.0.4 on 2024-09-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_reservationmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='train_name',
            field=models.TextField(null=True),
        ),
    ]
