# Generated by Django 4.0.4 on 2024-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_schedulemodel_email_schedulemodel_train_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemodel',
            name='email',
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='station_name',
            field=models.TextField(null=True),
        ),
    ]
