# Generated by Django 5.0.3 on 2024-09-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_alter_reservationmodel_shedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.trainsmodel'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='train_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='shedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.schedulemodel'),
        ),
    ]
