# Generated by Django 5.0.3 on 2024-09-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_reservationmodel_train_reservationmodel_train_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='cancelstatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
