# Generated by Django 5.0.3 on 2024-09-25 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0017_reservationmodel_cancelstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_station', models.TextField()),
                ('to_station', models.TextField()),
                ('trainclass', models.TextField()),
                ('no_seat', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('card_number', models.TextField()),
                ('nameon_card', models.TextField()),
                ('cvvnumber', models.TextField()),
                ('expiry', models.DateField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.trainsmodel')),
            ],
        ),
    ]
