# Generated by Django 5.0.3 on 2024-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='reservation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
